[sourceNode]
node = "http://localhost:6000"

totalNodesChecked = 189

successfulNodes = {
    "http://95.216.163.64:26657": "1",
    "http://195.14.6.178:26657": "345001",
    "http://65.108.66.220:26657": "1",
    "http://184.174.36.150:26657": "1",
    "http://162.55.245.144:2401": "268622",
    "http://65.108.238.215:27657": "315001",
    "http://136.243.88.91:6051": "1",
    "http://51.159.223.25:30657": "1",
    "http://141.94.135.203:26657": "298006",
    "http://54.39.128.229:26657": "328001",
    "http://88.99.219.120:43657": "294476",
    "http://5.9.10.222:26657": "173316",
    "http://75.119.151.144:26657": "312001",
    "http://localhost:6000": "269001",
    "http://142.132.202.87:26698": "173316",
    "http://138.201.85.176:20159": "1",
    "http://65.108.238.61:13657": "1",
    "http://135.181.118.61:26657": "1",
}

unsuccessfulNodes = [
    "http://142.132.211.91:12057",
    "http://148.251.11.99:12057",
    "http://88.198.52.89:12057",
    "http://23.88.74.54:12057",
    "http://138.201.63.38:26687",
    "http://95.216.245.247:12057",
    "http://65.21.27.176:26657",
    "http://74.118.136.190:26657",
    "http://34.106.169.75:26657",
    "http://143.198.16.189:26657",
    "http://65.108.230.26:26657",
    "http://65.109.92.79:11657",
    "http://35.87.17.153:26657",
    "http://65.109.94.221:41657",
    "http://51.79.19.101:26657",
    "http://49.12.120.56:26657",
    "http://116.202.238.252:6000",
    "http://",
    "http://136.243.69.100:43657",
    "http://176.9.155.156:11657",
    "http://141.94.73.39:43657",
    "http://185.225.232.196:11657",
    "http://65.21.196.102:26657",
    "http://65.109.106.211:22657",
    "http://65.108.106.252:26667",
    "http://65.108.103.17:26664",
    "http://158.220.86.129:26667",
    "http://135.181.16.163:26002",
    "http://185.188.249.62:35657",
    "http://135.181.48.106:26657",
    "http://34.74.136.237:26657",
    "http://20.250.38.245:26657",
    "http://51.79.82.227:6657",
    "http://89.58.32.218:27666",
    "http://31.128.228.155:657",
    "http://65.109.23.114:11657",
    "http://46.137.231.10:36657",
    "http://65.109.85.225:6051",
    "http://65.108.72.253:11657",
    "http://10.10.10.106:26657",
    "http://65.109.32.148:26117",
    "http://65.108.226.183:11657",
    "http://65.108.79.246:26677",
    "http://10.2.212.11:26657",
    "http://46.4.5.45:14957",
    "http://65.109.68.190:13457",
    "http://207.180.219.160:36657",
    "http://138.201.60.238:26657",
    "http://185.119.116.231:26657",
    "http://65.109.106.214:12057",
    "http://95.217.58.189:12057",
    "http://168.119.64.26:26657",
    "http://65.109.85.226:2011",
    "http://143.198.45.216:26001",
    "http://148.251.133.248:30057",
    "http://167.172.155.44:26002",
    "http://167.235.180.97:23457",
    "http://195.189.96.111:26657",
    "http://152.67.149.240:26657",
    "http://46.4.50.247:12057",
    "http://195.3.220.54:26657",
    "http://3.37.79.90:26657",
    "http://218.155.161.169:26657",
    "http://146.148.90.32:26657",
    "http://5.161.109.144:26657",
    "http://103.219.171.65:26657",
    "http://64.227.18.169:26657",
    "http://65.21.239.60:12057",
    "http://159.69.79.247:26657",
    "http://90.188.13.9:26657",
    "http://13.213.66.56:26657",
    "http://178.162.218.120:26657",
    "http://135.181.183.93:12057",
    "http://167.235.3.247:26637",
    "http://34.224.245.49:26657",
    "http://65.108.137.217:26657",
    "http://18.188.79.58:26657",
    "http://34.134.45.167:26657",
    "http://65.21.134.243:26682",
    "http://65.21.203.204:12057",
    "http://103.219.171.69:26657",
    "http://162.62.126.26:26657",
    "http://51.68.166.235:26657",
    "http://173.249.40.87:26657",
    "http://34.162.240.64:26657",
    "http://95.111.249.122:26657",
    "http://93.115.25.18:26657",
    "http://50.19.243.132:26657",
    "http://43.157.38.30:26657",
    "http://185.183.33.109:26657",
    "http://164.68.111.29:26657",
    "http://139.59.29.146:26657",
    "http://95.216.139.171:26657",
    "http://161.35.69.39:26657",
    "http://51.159.103.126:26657",
    "http://65.21.123.172:12057",
    "http://218.154.69.20:26657",
    "http://92.62.142.82:26657",
    "http://162.19.19.41:26657",
    "http://65.109.69.163:36657",
    "http://85.207.33.76:26657",
    "http://5.161.229.185:26657",
    "http://3.38.212.136:26657",
    "http://65.108.235.238:26657",
    "http://65.21.121.110:26657",
    "http://185.252.220.89:26657",
    "http://54.205.248.136:26657",
    "http://134.122.0.113:26657",
    "http://65.108.231.124:11657",
    "http://95.31.6.54:27657",
    "http://95.216.201.224:26657",
    "http://123.138.66.162:26657",
    "http://207.180.198.76:26657",
    "http://143.198.232.135:26657",
    "http://65.108.43.14:26657",
    "http://74.215.120.241:26657",
    "http://65.109.68.190:12057",
    "http://65.21.142.104:26657",
    "http://116.202.231.58:12057",
    "http://51.195.145.106:26657",
    "http://159.69.72.247:12057",
    "http://65.108.65.36:12057",
    "http://52.14.139.29:26657",
    "http://80.64.208.89:26657",
    "http://95.216.73.144:12057",
    "http://207.244.225.174:26657",
    "http://116.202.227.117:12057",
    "http://135.181.119.59:12057",
    "http://13.124.58.33:26657",
    "http://178.23.126.96:26657",
    "http://85.10.199.157:12057",
    "http://86.48.2.78:26657",
    "http://222.106.187.13:10002",
    "http://217.76.50.181:12057",
    "http://65.109.85.226:6051",
    "http://43.206.67.71:26657",
    "http://95.216.223.149:26657",
    "http://84.33.127.164:26657",
    "http://18.143.90.234:26657",
    "http://75.119.132.83:12057",
    "http://217.133.112.93:26657",
    "http://80.240.21.25:26657",
    "http://18.188.66.6:26657",
    "http://35.90.32.175:26657",
    "http://35.88.70.239:26657",
    "http://154.53.37.137:26657",
    "http://95.217.113.247:26657",
    "http://123.138.66.171:26657",
    "http://194.163.166.80:26657",
    "http://65.108.108.123:26657",
    "http://52.78.77.193:26657",
    "http://103.219.171.67:26657",
    "http://195.14.6.2:26657",
    "http://65.21.94.31:26657",
    "http://151.115.74.104:26657",
    "http://34.220.197.39:26657",
    "http://151.115.77.139:26657",
    "http://161.97.173.28:26657",
    "http://43.202.146.109:26657",
    "http://3.234.210.23:26657",
    "http://125.143.190.194:26657",
    "http://164.132.167.160:26657",
    "http://38.242.234.180:26657",
    "http://146.59.70.8:26657",
    "http://158.247.233.222:10002",
]

archiveNodes = [
    "http://95.216.163.64:26657",
    "http://136.243.88.91:6051",
    "http://138.201.85.176:20159",
    "http://51.159.223.25:30657",
    "http://65.108.238.61:13657",
    "http://65.108.66.220:26657",
    "http://135.181.118.61:26657",
    "http://184.174.36.150:26657",
]